name: Ionic CI/CD with Firebase Hosting Deployment

on:
  push:
    branches:
      - main

jobs:
  common-setup:
    uses: ./.github/workflows/common-setup.yml
    with:
      envFile: 'environment.maps.ts'
    secrets: inherit

  deploy:
    needs: common-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Environment File
        uses: actions/download-artifact@v3
        with:
          name: env-file

      - name: Copy Environment File
        run: cp env-file/environment.maps.ts src/environments/environment.maps.ts

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Ionic App
        run: npm run build -- --configuration=maps

      - name: Run Tests
        run: npm test -- --configuration=ci
        env:
          CI: true

      - name: Debug - List Files
        run: ls -la

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOEN390_AAB1A }}
          channelId: live
          projectId: soen390-aab1a
