name: Ionic CI/CD

on:
  push:
    branches:
      - workflow-setup
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Check if Secret exists
        run: echo "API_KEY=${{ secrets.FIREBASE_API_KEY }}"

      - name: Handle environment (Generate environment.ts)
        run: |
          cat <<EOF > src/environments/environment.ts
          export const environment = {
            production: false,
            firebaseConfig: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              databaseURL: '${{ secrets.FIREBASE_DATABASE_URL }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}',
            }
          };
          EOF
        shell: bash

      - name: Install Dependencies
        run: npm install

      - name: Build Ionic App
        run: npm run build -- --configuration=development

      - name: Run Tests
        run: npm test -- --configuration=ci
        env:
          CI: true
