name: Ionic CI/CD

on:
  push:
    branches:
      - workflow-setup
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Check if Secret exists
        run: echo "API_KEY=${{ secrets.FIREBASE_API_KEY }}"

      - name: Handle environment (Generate environment.ts)
        run: echo "export const environment = $(echo '${{ secrets.ENVIRONMENT_VARS }}' | jq -c .);" > src/environments/environment.ts
        shell: bash

      - name: Install Dependencies
        run: npm install

      - name: Build Ionic App
        run: npm run build -- --configuration=development

      - name: Run Tests
        run: npm test -- --configuration=ci
        env:
          CI: true
