name: Common Setup

on:
  workflow_call:
    inputs:
      envFile:
        description: 'The environment file name to generate'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Generate Environment File
        run: |
          cat <<EOF > src/environments/${{ inputs.envFile }}
          export const environment = {
            production: false,
            googleApiKey: "${{ secrets.GOOGLE_API_KEY }}",
            firebaseConfig: {
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              databaseURL: "${{ secrets.FIREBASE_DB_URL }}",
              projectId: "${{ secrets.FIREBASE_PID }}",
              storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              messagingSenderId: "${{ secrets.FIREBASE_MESSENGER_SENDER_ID }}",
              appId: "${{ secrets.FIREBASE_APP_ID }}"
            },
            mappedin: {
              mapId: "${{ secrets.MAPPEDIN_MAP_ID }}",
              key: "${{ secrets.MAPPEDIN_KEY }}",
              secret: "${{ secrets.MAPPEDIN_SECRET }}"
            }
          };
          EOF
        shell: bash

      - name: Upload Workspace Artifact
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: .
