name: SonarCloud Analysis

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  common-setup:
    uses: ./.github/workflows/common-setup.yml
    with:
      envFile: 'environment.maps.ts'
    secrets: inherit

  sonarcloud:
    needs: common-setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Workspace Artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Run Tests & Generate Coverage Report
        run: npm test -- --no-watch --code-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=soen390organization_soen390frontend
            -Dsonar.organization=soen390organization
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov-report/lcov.info
